### ISSUE TITLE
An error occurs here, would you please tell me what's going on? How to fix it?

### ISSUE THREAD

**Issue by Oo121oO** [1038lab/ComfyUI-RMBG#10]
[RMBG ERROR] Error in image processing: int() argument must be a string, a bytes-like object or a real number, not 'Image'
!!! Exception during processing !!! Error in image processing: int() argument must be a string, a bytes-like object or a real number, not 'Image'
Traceback (most recent call last):
  File "/autodl-fs/data/allan/ComfyUIOnline241118/custom_nodes/ComfyUI-RMBG/AILab_RMBG.py", line 396, in process_image
    mask_tensor = pil2tensor(mask)
  File "/autodl-fs/data/allan/ComfyUIOnline241118/custom_nodes/ComfyUI-RMBG/AILab_RMBG.py", line 74, in pil2tensor
    return torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/autodl-fs/data/allan/ComfyUIOnline241118/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/autodl-fs/data/allan/ComfyUIOnline241118/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/autodl-fs/data/allan/ComfyUIOnline241118/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/autodl-fs/data/allan/ComfyUIOnline241118/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/autodl-fs/data/allan/ComfyUIOnline241118/custom_nodes/ComfyUI-RMBG/AILab_RMBG.py", line 434, in process_image
    handle_model_error(f"Error in image processing: {str(e)}")
  File "/autodl-fs/data/allan/ComfyUIOnline241118/custom_nodes/ComfyUI-RMBG/AILab_RMBG.py", line 78, in handle_model_error
    raise RuntimeError(message)
RuntimeError: Error in image processing: int() argument must be a string, a bytes-like object or a real number, not 'Image'

I am sure about that all dependences work fine, cause [ComfyUI-BRIA_AI-RMBG](https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG) goes well here.

**Comment by Oo121oO** [comment]
BEN & INSPYRENET models work very well, only RMBG-2.0 goes wrong.

**Comment by 1038lab** [comment]
The error occurred because the image you provided wasn't in the expected format. The code expects either a valid PIL.Image or torch.Tensor, but the input might have been invalid or in the wrong format. Please ensure the image is properly loaded as a PIL image or tensor before processing. If you continue facing issues, feel free to share more details about the image you're using.

**Comment by Oo121oO** [comment]
> The error occurred because the image you provided wasn't in the expected format. The code expects either a valid PIL.Image or torch.Tensor, but the input might have been invalid or in the wrong format. Please ensure the image is properly loaded as a PIL image or tensor before processing. If you continue facing issues, feel free to share more details about the image you're using.

thanks for your reply.
Yes. I can guarantee that it is the same picture. I used the same picture to test the model. Other models also work well.

**Comment by Foxiaoy** [comment]
I get the same erro when python was 3.11.7 , but it works fine when python is 3.10.14 (ComfyUI version 0.3.9)

**Comment by Oo121oO** [comment]
> I get the same erro when python was 3.11.7 , but it works fine when python is 3.10.14 (ComfyUI version 0.3.9)

Here is my Python -V result:
Python 3.10.8
pillow version is 11.0.0 & numpy is 1.24.4 & torch is 2.4.0

**Comment by Oo121oO** [comment]
I solved it by modifying it as follows:
`
def pil2tensor(image):
    if isinstance(image, list):
        image = [np.array(img).astype(np.float32) / 255.0 for img in image]
        image = np.stack(image, axis=0)
        return torch.from_numpy(image)
    else:
        return torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0)

`

**Comment by 1038lab** [comment]
Glad to hear your proposed solution. If you could share the image you had the issue with, I’d like to take a look and better understand the issue.

**Comment by 1038lab** [comment]
you can update the custom node. try on the v1.3.1, it should fix the issue.
https://github.com/1038lab/ComfyUI-RMBG/blob/main/update.md#v131-20241225
